### ISSUE TITLE
Saviour of lost sould: make actions optional

### ISSUE THREAD

**Issue by IzzySoft** [Glorfindel83/SE-Userscripts#20]
First, thanks again for this very helpful script which helps me tremendously at SoftwareRecs.SE (where it feels like 90% of all incoming questions are off-topic)!

The new version added "deleting". Good idea, but not always wanted.¹ Then I noticed that if a comment already exists, there is a check-box to tick if I want to add another comment anyway. Which :bulb: gave me an idea:

Why not making all other actions optional as well (but other than with the "comment anyway", maybe "pre-checked")?

¹ <sub>for now I've disabled deletion by replacing the `|| isModerator` by `&& isModerator`, which mostly suits me as it enforces the "-3"</sub>

**Comment by Glorfindel83** [comment]
Thank you for your feedback. The deletion is (almost) always wanted on Meta
Stack Exchange, which is the site where it originated and most often used.
I can imagine it's different for SoftwareRecs.SE, and your plan for the
checkboxes sounds like a good idea. The 'delete' checkbox will be enabled
by default on Meta.SE and disabled on the other sites. I hope to have some
time later this week to implement it.

**Comment by IzzySoft** [comment]
That sounds great, thanks!

**Comment by Glorfindel83** [comment]
If you have the time, could you please test the new version? I've made almost all of the actions selectable, I hope it works for you. I did encounter some situations where my actions didn't get through, I'm still debugging those but I'm out of real-life test cases right now.

https://raw.githubusercontent.com/Glorfindel83/SE-Userscripts/master/saviour-of-lost-souls/saviour-of-lost-souls.user.js

**Comment by IzzySoft** [comment]
Thanks a lot! That seems to work perfectly. Just tried it and already had some different cases: even the pre-selection adjusted great. You're a genius :smiley: Consider this issue solved.

**Comment by Glorfindel83** [comment]
Thank you for the ideas, testing and the compliment :) I'll release this version to the public soon.
