### ISSUE TITLE
Pronoun Assistent: Limit pronoun display in chat to a certain length

### ISSUE THREAD

**Issue by mathcat4** [Glorfindel83/SE-Userscripts#53]
![long pronoun](https://i.imgur.com/usVLfWu.png)
I believe a "..." (or something of that sort) would be much better than every message of a certain user taking up multiple lines of space.

**Comment by mathcat4** [comment]
fair enough

**Comment by Peter-developer01** [comment]
cc @PlaceReporter99

**Comment by PlaceReporter99** [comment]
@Peter-developer01 what?

**Comment by Peter-developer01** [comment]
@PlaceReporter99

> @Peter-developer01 what?

Glorfindel83 wrote following:

> Not an issue with the script - **such pronoun indications should not be allowed on the network anyway.**

(emphasis mine)

I think you shouldn't have these page-breaking pronouns. I'd just remove that if this were my account.

**Comment by PlaceReporter99** [comment]
@Peter-developer01 This is not a malicious pronoun. I just like monkeys.

**Comment by Peter-developer01** [comment]
@PlaceReporter99 I see you don't understand why and what I say. I don't want to continue engaging in this conversation.
